config/routes.rb
Fablabs::Application.routes.draw do
  get "discourse/sso"
  get "discuss" => 'discourse#embed'
  resources :pages, only: [:show]
  use_doorkeeper
  require 'sidekiq/web'
  require "admin_constraint"
  mount Sidekiq::Web, at: '/sidekiq', constraints: AdminConstraint.new

  get "signout" => "sessions#destroy", :as => "signout"
  get "signin" => "sessions#new", :as => "signin"
  get '/robots.txt' => 'robots#robots', :format => :txt

  resources :sessions

  constraints subdomain: 'www' do
    # resources :discussions
    get "activity" => "activities#index", :as => "activity"
    resources :featured_images
    resources :organizations, only: [:index, :show, :new, :create, :edit, :update] do
      resources :lab_organizations, controller: 'organizations/lab_organizations' do
        member do
          post :accept
        end
      end
    end

    # resources :events

    get "verify_email(/:id)", to: "users#verify_email", as: "verify_email"

    %w(tos privacy-policy cookie-policy about choose_locale country_guess).each do |action|
      underscored = action.underscore
      get action => "static##{underscored}", as: underscored
    end

    resources :users
    resources :machines

    resources :brands

    resources :comments, only: [:create]

    resources :recoveries do
      collection do
        get :check_inbox
      end
    end

    get "signup" => "users#new", :as => "signup"
    get "settings" => "users#edit", :as => "settings"

    get "resend_verification_email" => "users#resend_verification_email"

    namespace :backstage do
      get "users/list" => "users#list"
      resources :users do
        resources :roles, controller: 'users/roles', only: [:index, :new, :create, :destroy]
      end
      resources :employees, only: :index
      resources :pages, expect: [:show]
      resources :organizations, only: [:index]
      resources :my_labs, only: [:index]
      resources :my_projects, only: [:index]
      resources :to_approve_labs, only: [:index]
      resources :labs do
        member do
          patch :approve
          patch :reject
          patch :remove
          patch :referee_approves
          patch :referee_rejects
          patch :request_more_info
          patch :referee_requests_admin_approval
          patch :admin_approves
          patch :admin_rejects
          patch :add_more_info
        end
      end
      root to: 'labs#index'
    end

    resources :employees do
      member do
        patch :approve
      end
    end

    get 'events' => 'events#main_index', as: 'events'
    resources :search, only: [:index]
    resources :projects do
      collection do
        get '/tags', to: :search
        get '/lab/:slug', to: :search
        get :map
        get :embed
      end
      get 'mapdata', on: :collection
      resources :steps do
        resources :links
      end
    end
    resources :referee_approval_processes, only: [:destroy]
    resources :contributions, only: [:destroy]
    resources :collaborations, only: [:destroy]
    resources :documents, only: [:destroy]
    resources :facilities, only: [:destroy]

    resources :users do
      resources :favourites, only: [:create, :destroy]
      resources :grades, only: [:create, :destroy]
    end

    get "/labs/docs/:page" => "labs#docs"
    resources :labs do
      resources :events
      resources :admin_applications
      resources :role_applications
      resources :employees
      resources :academics

      get 'mapdata', on: :collection
      # resources :discussions
      member do
        get :manage_admins
      end
      collection do
        get :map
        get :embed
        get :list
      end
    end

    root to: 'static#home'

  end

  constraints subdomain: 'api' do
    get '/' => 'static#api'
    namespace :api, path: '' do
      namespace :v0 do
        get 'me' => 'users#me'
        get 'users' => 'users#search'
        get 'labs/search' => 'labs#search'

        get 'search/all' => 'search#all'
        get 'search/labs' => 'search#labs'
        get 'search/projects' => 'search#projects'
        get 'search/machines' => 'search#machines'

        resources :coupons do
          get "redeem", on: :member
        end
        resources :labs do
          get :map, on: :collection
        end
        resources :projects do
          get :map, on: :collection
        end
      end
      namespace :v1 do
        get 'users' => 'users#search'

      end
    end
  end

  # constraints subdomain: 'api' do
  #   use_doorkeeper
  #   get '/' => 'static#api'
  #   api versions: 1, module: "api/v1" do
  #     get 'me' => 'users#show'
  #     resources :labs, only: [:index]
  #   end
  # end

  get ':id' => 'redirects#show'
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  include Authority::Abilities
  self.authorizer_name = 'EmployeeAuthorizer'

  belongs_to :user, touch: true
  belongs_to :lab, touch: true
  validates_presence_of :user, :lab, :job_title
  validates_uniqueness_of :user_id, scope: :lab_id

  after_create :auto_approve_for_admins
  before_destroy { user.revoke :admin, lab }

  scope :active, -> { includes(:user).with_approved_state.references(:user) }

  include Workflow
  workflow do
    state :unverified do
      event :approve, transitions_to: :approved
    end
    state :approved
  end

  def approve
    user.add_role :admin, lab
  end

private

  def auto_approve_for_admins
    approve! if user.present? and user.has_role?(:admin, lab)
  end

end

app/controllers/backstage/employees_controller.rb
class Backstage::EmployeesController < Backstage::BackstageController
  before_filter :require_admin

  def index
    @q = Employee.search(params[:q])
    @q.sorts = 'id desc' if @q.sorts.empty?
    @employees = @q.result.page(params[:page]).includes(:lab, :user).where("labs.workflow_state" => 'approved').with_unverified_state.order('employees.id DESC')
  end

  private
    def require_admin
      if current_user
        unless current_user.has_role? :superadmin
          return redirect_to backstage_labs_url, notice: "Not authorized"
        end
      else
        return redirect_to signin_url
      end
    end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  before_filter :require_login

  def new
    @lab = Lab.with_approved_state.friendly.find params[:lab_id]
    if current_user.applied_to?(@lab)
      redirect_to lab_url(@lab), notice: "You've already applied to work here"
    else
      @employee = @lab.employees.build
      authorize_action_for @employee
    end
  end

  def create
    @lab = Lab.with_approved_state.friendly.find params[:lab_id]
    @employee = @lab.employees.new employee_params.merge({user: current_user})
    authorize_action_for @employee
    if @employee.save
      track_activity @employee, @employee.user
      AdminMailer.delay.employee_applied(@employee.id)
      redirect_to lab_url(@lab), notice: "Thank you for applying"
    else
      render :new
    end
  end

  def update
    @employee = Employee.find params[:id]
    authorize_action_for @employee
    if @employee.update_attributes employee_params
      track_activity @employee, @employee.user
      redirect_to lab_employees_url(@employee.lab), notice: "Employee updated"
    else
      render :edit
    end
  end

  def index
    @lab = Lab.with_approved_state.friendly.find params[:lab_id]
    @employees = @lab.employees
  end

  def approve
    @employee = Employee.find(params[:id])
    if @employee.approve!
      UserMailer.delay.employee_approved(@employee.id)
      track_activity @employee, @employee.user
      redirect_to lab_employees_url(@employee.lab), notice: 'Employee approved'
    else
      redirect_to lab_employees_url(@employee.lab), notice: 'Failed'
    end
  end

  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy
    track_activity @employee, @employee.user
    redirect_to lab_url(@employee.lab), notice: 'Employee removed'
  end

  def edit
    @employee = Employee.find(params[:id])
    authorize_action_for @employee
  end

private

  def employee_params
    params.require(:employee).permit(
      :user_id,
      :lab_id,
      :ordinal,
      :job_title,
      :email,
      :phone,
      :description
    )
  end

end

app/views/employees/_employee.html.haml
= content_tag_for :div, employee, class: 'media' do
  .pull-left
    = image_tag employee.user.avatar_url, class: 'avatar med'
  .media-body
    = link_to employee.user, employee.user
    .job-title= employee.job_title
    .description= employee.description
    = employee.current_state

    = link_to "Edit", edit_employee_path(employee), class: 'button tiny'
    = link_to "Remove", employee, method: :delete, class: 'button tiny alert'

    - employee.current_state.events.keys.each do |event|
      = button_to event.capitalize, {controller: 'employees', action: event, id: employee.id }, method: :patch, class: 'button tiny'

app/views/employees/_form.html.haml
= simple_form_for [lab,employee] do |f|
  = render "form_errors", resource: employee
  -# = f.association :user

  %fieldset
    %legend Role Details
    = f.input :job_title, input_html: { placeholder: "e.g. Fab Lab Manager" }, autofocus: f.object.new_record?
    = f.input :description, as: 'string', label: 'Job description/responsibilities'

  -# = f.input :is_public
  -# = f.input :is_admin

  %fieldset
    %legend Public Contact Details
    %p.hint These are optional, they will be listed publicly on #{employee.lab}'s page. We recommend that you at least add a direct email address if possible. It will be obfuscated in the source code to prevent SPAM bots from harvesting it.
    = f.input :email, label: "Direct Email"
    = f.input :phone, label: "Direct Phone Number"

  = f.submit (f.object.new_record? ? "Send Application" : "Update"), class: 'btn btn-primary'

app/views/employees/edit.html.haml
.row
  .col-lg-12
    = title "Edit Employee"
    = render "form", lab: @lab, employee: @employee

app/views/employees/index.html.haml
.row
  .col-lg-12
    = render "labs/breadcrumbs", lab: @lab
.row
  .col-lg-12
    = title "Employees at #{@lab}"

    .panel
      %p
        %strong Remember before you approve people
        All employees will have FULL ADMIN RIGHTS for #{@lab}. Soon you will be able to edit this.
    %table.table
      %thead
        %tr
          %th Employee
          %th Date Added
          %th{colspan: 100} Actions

      - @lab.employees.order('id DESC').each do |employee|
        %tr
          %td
            .user
              %strong= link_to employee.user, employee.user
            .job-title
              %strong= employee.job_title
            .description= employee.description
            .phone= employee.phone
            .email= mail_to employee.email, employee.email

          %td= employee.created_at.to_s(:short)
          %td.text-right
            = link_to "Edit", edit_employee_path(employee), class: 'btn btn-primary'
            = link_to "Remove", employee, method: :delete, class: 'btn btn-danger', data: { confirm: "Are you sure you want to remove #{employee.user} from #{@lab}? They will no longer be able to manage #{@lab}."}
            - employee.current_state.events.keys.each do |event|
              = button_to event.capitalize, {controller: 'employees', action: event, id: employee.id }, method: :patch, class: 'btn btn-danger'

  -#   %h4 Approved Employees
  -#   = render @lab.employees.active

  -# .col-lg-6
  -#   %h4 Unverified Employees
  -#   = render @lab.employees.with_unverified_state

app/views/employees/new.html.haml
.row
  .col-lg-12
    = title "Employee Application"
    = render "form", lab: @lab, employee: @employee