config/routes.rb
Fablabs::Application.routes.draw do
  get "discourse/sso"
  get "discuss" => 'discourse#embed'
  resources :pages, only: [:show]
  use_doorkeeper
  require 'sidekiq/web'
  require "admin_constraint"
  mount Sidekiq::Web, at: '/sidekiq', constraints: AdminConstraint.new

  get "signout" => "sessions#destroy", :as => "signout"
  get "signin" => "sessions#new", :as => "signin"
  get '/robots.txt' => 'robots#robots', :format => :txt

  resources :sessions

  constraints subdomain: 'www' do
    # resources :discussions
    get "activity" => "activities#index", :as => "activity"
    resources :featured_images
    resources :organizations, only: [:index, :show, :new, :create, :edit, :update] do
      resources :lab_organizations, controller: 'organizations/lab_organizations' do
        member do
          post :accept
        end
      end
    end

    # resources :events

    get "verify_email(/:id)", to: "users#verify_email", as: "verify_email"

    %w(tos privacy-policy cookie-policy about choose_locale country_guess).each do |action|
      underscored = action.underscore
      get action => "static##{underscored}", as: underscored
    end

    resources :users
    resources :machines

    resources :brands

    resources :comments, only: [:create]

    resources :recoveries do
      collection do
        get :check_inbox
      end
    end

    get "signup" => "users#new", :as => "signup"
    get "settings" => "users#edit", :as => "settings"

    get "resend_verification_email" => "users#resend_verification_email"

    namespace :backstage do
      get "users/list" => "users#list"
      resources :users do
        resources :roles, controller: 'users/roles', only: [:index, :new, :create, :destroy]
      end
      resources :employees, only: :index
      resources :pages, expect: [:show]
      resources :organizations, only: [:index]
      resources :my_labs, only: [:index]
      resources :my_projects, only: [:index]
      resources :to_approve_labs, only: [:index]
      resources :labs do
        member do
          patch :approve
          patch :reject
          patch :remove
          patch :referee_approves
          patch :referee_rejects
          patch :request_more_info
          patch :referee_requests_admin_approval
          patch :admin_approves
          patch :admin_rejects
          patch :add_more_info
        end
      end
      root to: 'labs#index'
    end

    resources :employees do
      member do
        patch :approve
      end
    end

    get 'events' => 'events#main_index', as: 'events'
    resources :search, only: [:index]
    resources :projects do
      collection do
        get '/tags', to: :search
        get '/lab/:slug', to: :search
        get :map
        get :embed
      end
      get 'mapdata', on: :collection
      resources :steps do
        resources :links
      end
    end
    resources :referee_approval_processes, only: [:destroy]
    resources :contributions, only: [:destroy]
    resources :collaborations, only: [:destroy]
    resources :documents, only: [:destroy]
    resources :facilities, only: [:destroy]

    resources :users do
      resources :favourites, only: [:create, :destroy]
      resources :grades, only: [:create, :destroy]
    end

    get "/labs/docs/:page" => "labs#docs"
    resources :labs do
      resources :events
      resources :admin_applications
      resources :role_applications
      resources :employees
      resources :academics

      get 'mapdata', on: :collection
      # resources :discussions
      member do
        get :manage_admins
      end
      collection do
        get :map
        get :embed
        get :list
      end
    end

    root to: 'static#home'

  end

  constraints subdomain: 'api' do
    get '/' => 'static#api'
    namespace :api, path: '' do
      namespace :v0 do
        get 'me' => 'users#me'
        get 'users' => 'users#search'
        get 'labs/search' => 'labs#search'

        get 'search/all' => 'search#all'
        get 'search/labs' => 'search#labs'
        get 'search/projects' => 'search#projects'
        get 'search/machines' => 'search#machines'

        resources :coupons do
          get "redeem", on: :member
        end
        resources :labs do
          get :map, on: :collection
        end
        resources :projects do
          get :map, on: :collection
        end
      end
      namespace :v1 do
        get 'users' => 'users#search'

      end
    end
  end

  # constraints subdomain: 'api' do
  #   use_doorkeeper
  #   get '/' => 'static#api'
  #   api versions: 1, module: "api/v1" do
  #     get 'me' => 'users#show'
  #     resources :labs, only: [:index]
  #   end
  # end

  get ':id' => 'redirects#show'
end

app/controllers/api/v0/search_controller.rb
class Api::V0::SearchController < Api::V0::ApiController
  include LabsSearch
  include ProjectsOperations

  def all
    @results = search_labs(params[:q]).page(params['page']).per(params['per']) |  search_projects(params[:q]).page(params['page']).per(params['per'])

    respond_to do |format|
      format.json { render json: @results, each_serializer: SearchResultSerializer }
      # format.csv { send_data @results.to_csv }
    end

  end

  def labs
    @labs = search_labs(params[:q]).page(params['page']).per(params['per'])
    render json: @labs, each_serializer: LabSerializer
  end

  def projects
    @projects = search_projects(params[:q]).page(params['page']).per(params['per'])
    render json: @projects
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  include LabsSearch
  include ProjectsOperations
  include UsersOperations

  before_filter :require_login, except: :index

  def index
    @labs = search_labs(params[:q])
    @projects = search_projects(params[:q])
    @users = search_users(params[:q])

    @results = @labs + @projects + @users

    respond_to do |format|
      format.html
    end
  end

end

app/views/search/_lab.html.haml
- cache ["v1-#{I18n.locale}", lab] do
  = content_tag_for :div, lab, class: 'media', itemscope: true, itemtype: "http://data-vocabulary.org/Organization" do
    .img.pull-left
      = link_to lab do
        = image_tag lab.avatar.thumb("100x100").url, class: 'med avatar', itemprop: "logo"
    .media-body
      = link_to lab, class: 'name' do
        %span.name{itemprop: "name"}= lab
      %span.url.microdata{itemprop: "url"}= lab_url(lab, {locale: nil})
      .lab-location
        - if lab.short_address(!params[:country]).present?
          = fa_icon "map-marker"
          %span.short_address{itemprop: "addressLocality"}= lab.short_address(!params[:country])
          %span.microdata.country{itemprop: "country"}= lab.country_code
        - if lab.email.present?
          = fa_icon "envelope-o"
          %span.email= mail_to(lab.email, lab.email)
        - if lab.phone.present?
          = fa_icon "phone"
          %span.telephone{itemprop: "telephone"}= lab.phone
      %p.lab-blurb.truncate{itemprop: "description"}= lab.blurb

app/views/search/_project.html.haml
- cache ["v1", project] do
  = content_tag_for :div, project, class: 'media', itemscope: true do
    .img.pull-left
      = link_to project.owner do
        = image_tag project.owner.avatar_url, class: 'avatar'
    .media-body
      = link_to project.title, project
      %span
        = icon('map-marker')
        = link_to project.lab do
          = project.lab.name
      %p
        = truncate strip_tags(restricted_markdown(project.description)), :length => 120, :omission => "..."
        = link_to "more", project

app/views/search/_user.html.haml
= content_tag_for :div, user do
    = link_to user, user

app/views/search/index.html.haml
- title "Search"
.row
  .col-lg-8.content
    .row
      .col-lg-12
        -# %dl.sub-nav.right.order-by
        -#   %dt Order by:
        -#   %dd= select_tag :order, ['title','title']

    - if params[:query].present?
      .search-results
        -# %button.close{type: "button", data: { dismiss: "alert"}, aria: { hidden: true}} ×
        = link_to "×", labs_path, class: 'close right'
        #{pluralize @results.size, "search result"} for
        %strong= params[:query]
    - if @labs.size > 0
      .row
        %h4 Labs
        .labs= render @labs
    - if @projects.size > 0
      .row
        %h4 Projects
        .projects= render @projects
    - if @users.size > 0
      .row
        %h4 People
        .users= render @users
    - if @results.empty?
      %p We could not find what you were looking for. Maybe you can try again.


  .col-lg-4