config/routes.rb
Fablabs::Application.routes.draw do
  get "discourse/sso"
  get "discuss" => 'discourse#embed'
  resources :pages, only: [:show]
  use_doorkeeper
  require 'sidekiq/web'
  require "admin_constraint"
  mount Sidekiq::Web, at: '/sidekiq', constraints: AdminConstraint.new

  get "signout" => "sessions#destroy", :as => "signout"
  get "signin" => "sessions#new", :as => "signin"
  get '/robots.txt' => 'robots#robots', :format => :txt

  resources :sessions

  constraints subdomain: 'www' do
    # resources :discussions
    get "activity" => "activities#index", :as => "activity"
    resources :featured_images
    resources :organizations, only: [:index, :show, :new, :create, :edit, :update] do
      resources :lab_organizations, controller: 'organizations/lab_organizations' do
        member do
          post :accept
        end
      end
    end

    # resources :events

    get "verify_email(/:id)", to: "users#verify_email", as: "verify_email"

    %w(tos privacy-policy cookie-policy about choose_locale country_guess).each do |action|
      underscored = action.underscore
      get action => "static##{underscored}", as: underscored
    end

    resources :users
    resources :machines

    resources :brands

    resources :comments, only: [:create]

    resources :recoveries do
      collection do
        get :check_inbox
      end
    end

    get "signup" => "users#new", :as => "signup"
    get "settings" => "users#edit", :as => "settings"

    get "resend_verification_email" => "users#resend_verification_email"

    namespace :backstage do
      get "users/list" => "users#list"
      resources :users do
        resources :roles, controller: 'users/roles', only: [:index, :new, :create, :destroy]
      end
      resources :employees, only: :index
      resources :pages, expect: [:show]
      resources :organizations, only: [:index]
      resources :my_labs, only: [:index]
      resources :my_projects, only: [:index]
      resources :to_approve_labs, only: [:index]
      resources :labs do
        member do
          patch :approve
          patch :reject
          patch :remove
          patch :referee_approves
          patch :referee_rejects
          patch :request_more_info
          patch :referee_requests_admin_approval
          patch :admin_approves
          patch :admin_rejects
          patch :add_more_info
        end
      end
      root to: 'labs#index'
    end

    resources :employees do
      member do
        patch :approve
      end
    end

    get 'events' => 'events#main_index', as: 'events'
    resources :search, only: [:index]
    resources :projects do
      collection do
        get '/tags', to: :search
        get '/lab/:slug', to: :search
        get :map
        get :embed
      end
      get 'mapdata', on: :collection
      resources :steps do
        resources :links
      end
    end
    resources :referee_approval_processes, only: [:destroy]
    resources :contributions, only: [:destroy]
    resources :collaborations, only: [:destroy]
    resources :documents, only: [:destroy]
    resources :facilities, only: [:destroy]

    resources :users do
      resources :favourites, only: [:create, :destroy]
      resources :grades, only: [:create, :destroy]
    end

    get "/labs/docs/:page" => "labs#docs"
    resources :labs do
      resources :events
      resources :admin_applications
      resources :role_applications
      resources :employees
      resources :academics

      get 'mapdata', on: :collection
      # resources :discussions
      member do
        get :manage_admins
      end
      collection do
        get :map
        get :embed
        get :list
      end
    end

    root to: 'static#home'

  end

  constraints subdomain: 'api' do
    get '/' => 'static#api'
    namespace :api, path: '' do
      namespace :v0 do
        get 'me' => 'users#me'
        get 'users' => 'users#search'
        get 'labs/search' => 'labs#search'

        get 'search/all' => 'search#all'
        get 'search/labs' => 'search#labs'
        get 'search/projects' => 'search#projects'
        get 'search/machines' => 'search#machines'

        resources :coupons do
          get "redeem", on: :member
        end
        resources :labs do
          get :map, on: :collection
        end
        resources :projects do
          get :map, on: :collection
        end
      end
      namespace :v1 do
        get 'users' => 'users#search'

      end
    end
  end

  # constraints subdomain: 'api' do
  #   use_doorkeeper
  #   get '/' => 'static#api'
  #   api versions: 1, module: "api/v1" do
  #     get 'me' => 'users#show'
  #     resources :labs, only: [:index]
  #   end
  # end

  get ':id' => 'redirects#show'
end

app/models/discourse_service/lab.rb
module DiscourseService
  class Lab < Entity
    def name
      "Discussion about #{@entity.name}"
    end

    def description
      "#{@entity.description}

This is the general thread for discussing the lab; the thread is also visible on its page at #{url}
      "
    end

    def url
      "#{Figaro.env.url}/labs/#{@entity.slug}"
    end

    def category
      Figaro.env.discourse_lab_category
    end

    def creator
      @entity.creator
    end
  end
end

app/controllers/api/v0/labs_controller.rb
class Api::V0::LabsController < Api::V0::ApiController

  def index
    @labs = Lab.with_approved_state.includes(:links)
    respond_to do |format|
      format.json { respond_with @labs }
      # http://railscasts.com/episodes/362-exporting-csv-and-excel
      # format.csv { send_data @labs.to_csv }
      # format.xls { send_data @labs.to_csv(col_sep: "\t") }
    end
  end

  def show
    respond_with Lab.with_approved_state.includes(:links).find(params[:id])
  end

  def map
    respond_with Lab.select(:latitude,:longitude,:name,:id)
      .with_approved_state.includes(:links),
      each_serializer: MapSerializer
  end

  def search
    @labs = Lab.where("slug LIKE ? or name LIKE ?", "%#{params[:q]}%", "%#{params[:q].capitalize}%")
    render json: @labs, each_serializer: LabSerializer
  end

end

app/controllers/api/v1/labs_controller.rb
class Api::V1::LabsController < Api::V1::ApiController

  caches :index, caches_for: 10.minutes

  def index
    expose Lab.with_approved_state.includes(:links)
  end

end

app/controllers/backstage/backstage_controller.rb
class Backstage::BackstageController < ApplicationController
  before_filter :require_admin

private

  def require_admin
    if current_user
      unless superadmin or referee
        return redirect_to root_url, notice: "Not authorized"
      end
    else
      return redirect_to signin_url
    end
  end

  def superadmin
    current_user.has_role? :superadmin
  end

  def referee
    current_user.is_referee? or current_user.is_unique_referee?
  end
end

app/controllers/backstage/employees_controller.rb
class Backstage::EmployeesController < Backstage::BackstageController
  before_filter :require_admin

  def index
    @q = Employee.search(params[:q])
    @q.sorts = 'id desc' if @q.sorts.empty?
    @employees = @q.result.page(params[:page]).includes(:lab, :user).where("labs.workflow_state" => 'approved').with_unverified_state.order('employees.id DESC')
  end

  private
    def require_admin
      if current_user
        unless current_user.has_role? :superadmin
          return redirect_to backstage_labs_url, notice: "Not authorized"
        end
      else
        return redirect_to signin_url
      end
    end

end

app/controllers/backstage/labs_controller.rb
class Backstage::LabsController < Backstage::BackstageController
  include LabsOperations

  def index
    if current_user.has_role? :superadmin
      @q = Lab.includes(:creator).search(params[:q])
    elsif current_user.is_referee? or current_user.is_unique_referee?
      @q = Lab.includes(:creator).where("referee_id IN (?)",  current_user.admin_labs.map{ |u| u.resource_id }).search(params[:q])
    end

    @q.sorts = 'id desc' if @q.sorts.empty?
    @labs = @q.result.page(params[:page]).per(params[:per])
    #(distinct: true)
    # @labs = Lab.order(id: :desc)
  end

  def show
    @lab = Lab.friendly.find(params[:id])
  end

  def edit
    @lab = Lab.friendly.find(params[:id])
  end

  def update
    @lab = Lab.friendly.find(params[:id])
    if @lab.update_attributes(lab_params)
      redirect_to backstage_labs_path, notice: "Lab updated"
    else
      render :edit
    end
  end

  %w( approve
      reject
      remove
      referee_approves
      referee_rejects
      approve
      reject
      remove
      referee_requests_admin_approval
      request_more_info
      need_more_info
    ).each do |verb|
    define_method(verb) do
      verbed = action_to_verb[verb.parameterize.underscore.to_sym]
      @lab = Lab.friendly.find(params[:id])
      if @lab.send("#{verb}!", current_user)
        lab_send_action("#{verbed}")
        redirect_to backstage_labs_path, notice: "Lab #{verbed.tr('_', ' ')}"
      else
        redirect_to backstage_lab_path(@lab), notice: "Could not #{verb} lab"
      end
    end
  end

  private
    def lab_params
      params.require(:lab).permit!
    end

end

app/controllers/backstage/my_labs_controller.rb
class Backstage::MyLabsController < ApplicationController
  def index
    @q = current_user.created_labs.search(params[:q])

    @q.sorts = 'id desc' if @q.sorts.empty?
    @labs = @q.result.page(params[:page]).per(params[:per])
  end
end

app/controllers/backstage/my_projects_controller.rb
class Backstage::MyProjectsController < ApplicationController
  def index
    @q = current_user.created_projects.search(params[:q])

    @q.sorts = 'id desc' if @q.sorts.empty?
    @projects = @q.result.page(params[:page]).per(params[:per])
  end
end

app/controllers/backstage/organizations_controller.rb
class Backstage::OrganizationsController < Backstage::BackstageController

  def index
    @q = Organization.search(params[:q])
    @organizations = @q.result.page(params[:page])
  end
end

app/controllers/backstage/pages_controller.rb
class Backstage::PagesController < Backstage::BackstageController

  before_filter :require_admin

  def index
    @pages = Page.page(params[:page]).order('position asc')
  end

  def new
    @page = Page.new
  end

  def create
    @page = Page.new(page_params)
    if @page.save
      redirect_to [:edit, :backstage, @page], notice: 'Page created'
    else
      render :new
    end
  end

  def edit
    find_page
  end

  def update
    find_page
    if @page.update(page_params)
      redirect_to [:edit, :backstage, @page], notice: 'Page updated'
    else
      render :edit
    end
  end

  def destroy
    find_page
    @page.destroy
    redirect_to [:backstage, :pages], notice: 'Page deleted'
  end

  private

  def find_page
    @page = Page.friendly.find(params[:id])
  end

  def page_params
    params.require(:page).permit(:title, :content, :published, :position, :slug)
  end
end

app/controllers/backstage/to_approve_labs_controller.rb
class Backstage::ToApproveLabsController < ApplicationController

  def index
    @q = Lab.where(id: current_user.referee_labs.map(&:id)).search(params[:q])

    @q.sorts = 'id desc' if @q.sorts.empty?
    @labs = @q.result.page(params[:page]).per(params[:per])
  end
end

app/controllers/backstage/users/roles_controller.rb
class Backstage::Users::RolesController < Backstage::BackstageController
  before_filter :require_superadmin
  before_action :find_user

  def index
    @roles = @user.roles
  end

  def new
    @role = @user.roles.build
  end

  def create
    @user.add_role(params[:role][:name])
    redirect_to [:backstage, @user, :roles], notice: 'Added role'
  end

  def destroy
    @role = @user.roles.find(params[:id])
    @user.remove_role(@role.name)
    redirect_to [:backstage, @user, :roles], notice: 'Removed role'
  end

  private

  def role_params
    params.require(:role).permit(:name)
  end

  def find_user
    @user = User.friendly.find(params[:user_id])
  end
end

app/controllers/backstage/users_controller.rb
class Backstage::UsersController < Backstage::BackstageController
  before_filter :require_admin

  def index
    @q = User.search(params[:q])
    @q.sorts = 'id desc' if @q.sorts.empty?
    @users = @q.result.page(params[:page])
  end

  def show
    @user = User.friendly.find(params[:id])
  end

  def edit
    @user = User.friendly.find(params[:id])
  end

  def update
    @user = User.friendly.find(params[:id])
    if @user.update_attributes user_params
      redirect_to backstage_users_path, notice: "User updated"
    else
      render :edit
    end
  end

  def list
    @users = User.all.map { |e| "#{e.full_name} - #{e.email}" }
    render text: @users.to_csv
  end

private

  def user_params
    params.require(:user).permit!
  end


  def require_admin
    if current_user
      unless current_user.has_role? :superadmin
        return redirect_to backstage_labs_url, notice: "Not authorized"
      end
    else
      return redirect_to signin_url
    end
  end

end

app/controllers/labs_controller.rb
class LabsController < ApplicationController
  include LabsOperations

  before_filter :require_login, except: [:index, :map, :show, :mapdata, :embed, :list]
  after_filter :allow_iframe, only: [:embed, :list]

  # authorize_actions_for Lab, actions: { map: :read, manage_admins: :update}

  def embed
    @labs = Lab.with_approved_state
    # render :embed, layout: false
    render layout: "embed"
  end

  def map
    @labs = Lab.with_approved_state
  end

  def list
    if params[:country]
      params["country"].downcase!
    end
    @labs = Lab.with_approved_state.order('LOWER(name) ASC').in_country_code(params["country"]).page(params['page']).per(params['per'])
    render layout: "embed"
  end

  def mapdata
    @labs = Lab.with_approved_state.select(:id, :name, :slug, :latitude, :longitude, :kind)
    render json: @labs, each_serializer: MapSerializer
  end

  def index
    if params[:country]
      params["country"].downcase!
    end
    all_labs = Lab.search_for(params[:query]).with_approved_state
    @countries = Lab.country_list_for all_labs
    @count = all_labs.size
    @labs = all_labs.order('LOWER(name) ASC').in_country_code(params["country"]).page(params['page']).per(params['per'])

    respond_to do |format|
      format.html
      format.json { render json: @labs }
      # format.csv { send_data @labs.to_csv }
    end
  end

  def new
    @lab = current_user.created_labs.build
    @lab.employees.build
    @lab.links.build
    authorize_action_for @lab
  end

  def create
    @lab = current_user.created_labs.build lab_params
    @lab.employees.first.assign_attributes(user: current_user, lab: @lab)
    authorize_action_for @lab
    if @lab.save
      sends_emails("submitted")
      redirect_to labs_path, notice: "Thanks for adding your lab. We shall review your application and be in touch."
    else
      # @lab.employees.build if @lab.employees.empty?
      @lab.links.build
      render :new
    end
  end

  def show
    begin
      @lab = with_approved_or_pending_state(params[:id])
    rescue ActiveRecord::RecordNotFound
      return redirect_to root_path, notice: "Lab not found"
    end
    # @people = [@lab.creator]
    @employees = @lab.employees.includes(:user).active.order('employees.id ASC')
    @machines = @lab.machines.includes(:brand, :tags)
    @events = @lab.events.order('starts_at ASC').includes(:lab)
    @academics = @lab.academics.includes(:user).order('users.first_name ASC')
    @years = @academics.map(&:started_in).uniq.sort.reverse
    @nearby_labs = @lab.nearby_labs(false, 1000)
    @nearby_labs = @nearby_labs.limit(5) if @nearby_labs
    authorize_action_for @lab
  end

  def destroy
    @lab = Lab.friendly.find(params[:id])
    authorize_action_for @lab
    @lab.delete
    redirect_to labs_path, notice: "Lab deleted"
  end

  def edit
    @lab = Lab.friendly.find(params[:id])
    @lab.links.build
    authorize_action_for @lab
  end

  def update
    @lab = Lab.friendly.find(params[:id])
    authorize_action_for @lab
    if @lab.update_attributes lab_params
      track_activity @lab
      update_workflow_state
      redirect_to lab_url(@lab), notice: "Lab was successfully updated"
    else
      @lab.links.build
      render :edit
    end
  end

  def manage_admins
    @lab = Lab.friendly.find(params[:id])
    authorize_action_for @lab
    @admins = @lab.admins
    @users = User.all# - User.with_role(:admin) - [current_user]
  end

  def docs
    render template: "labs/docs/#{params[:page]}"
  end

private

  def allow_iframe
    response.headers.delete "X-Frame-Options"
    # From http://jerodsanto.net/2013/12/rails-4-let-specific-actions-be-embedded-as-iframes/
  end

  def lab_params
    params.require(:lab).permit(
      :activity_status,
      :activity_start_at,
      :activity_inaugurated_at,
      :activity_closed_at,
      :avatar,
      :header,
      :kind,
      :parent_id,
      :referee_id,
      :tools_list,
      :geocomplete,
      :name,
      :blurb,
      :description,
      :slug,
      :address_1,
      :address_2,
      :city,
      :county,
      :postal_code,
      :country_code,
      :latitude,
      :longitude,
      :zoom,
      :address_notes,
      :phone,
      :email,
      :application_notes,
      :tools_list,
      :tools,
      :network,
      :programs,
      capabilities: [ ],
      facilities_attributes: [:id, :thing_id, '_destroy' ],
      links_attributes: [ :id, :link_id, :url, '_destroy' ],
      referee_approval_processes_attributes: [ :referee_lab_id, '_destroy' ],
      employees_attributes: [ :id, :job_title, :description ]
    )
  end

end

app/helpers/backstage/my_labs_helper.rb
module Backstage::MyLabsHelper
end

app/helpers/backstage/to_approve_labs_helper.rb
module Backstage::ToApproveLabsHelper
end

app/helpers/organizations/labs_helper.rb
module Organizations::LabsHelper
end

app/views/backstage/labs/_labs.html.haml
.well
  = search_form_for @q, url: url_form, builder: SimpleForm::FormBuilder do |f|
    = f.input :name_or_city_cont, label: "Name"
    .row
      .col-lg-3
        = f.input :is_referee_true, as: :boolean, label: "Is referee"
      .col-lg-3
        = f.input :discourse_id_not_null, as: :boolean, label: "With discourse ID"
      .col-lg-3
        = f.input :discourse_id_null, as: :boolean, label: "Without discourse ID"
      .col-lg-3
        = f.input :discourse_errors_not_null, as: :boolean, label: "With discourse sync errors"
    .row
      .col-lg-4
        = f.input :country_code_eq, as: 'country', label: 'Country', iso_codes: true, include_blank: 'ALL'
      .col-lg-4
        = f.input :workflow_state_eq, collection: Lab.workflow_spec.state_names, label: "State", include_blank: 'ALL'
      .col-lg-3
        = f.submit "Filter", class: 'btn btn-success btn-lg'

= page_entries_info @labs
%table.table
  %thead
    %tr
      %th= sort_link @q, :id, 'ID'
      %th= sort_link @q, :name, 'Name'
      %th Country
      %th
        Creator
        = sort_link @q, 'creator_first_name', 'First'
        = sort_link @q, 'creator_last_name', 'Last'

      %th= sort_link @q, :state, 'State'
  %tbody
    - @labs.each do |lab|
      = content_tag_for :tr, lab, {class: lab.current_state} do
        %td= lab.id
        %td= link_to lab, backstage_lab_path(lab)
        %td= lab.country
        %td= link_to lab.creator, lab.creator
        %td= lab.current_state

= paginate @labs

app/views/backstage/labs/edit.html.haml
= render "backstage/header"
= title "Editing #{@lab}"
= simple_form_for [:backstage, @lab] do |f|
  = render "form_errors", resource: @lab

  .edit-lab

  %fieldset
    %legend Basic Details
    .row
      .col-lg-12
        %h5
          Name, description and slug of your Lab
        = f.input :name
        = f.input :blurb
        = f.input :description
        = f.input :slug
    .row
      .col-lg-12
        %h5
          Kind of Lab
        %p
          What kind of Fab Lab is your Lab?
        - Lab::Kinds.each_with_index do |m, index|
          .col-lg-2
            .radio-inline
              %span
                = f.radio_button :kind, index
                %label.radio{style: "width: 160px;"}
                  = m.humanize.titleize

  %fieldset
    %legend
      Approval process
    .row
      .col-lg-12
        %h5
          Referee Labs
        %p
          These are your Referee Labs. Please contact them in case you have any question regarding your approval process.
        .selections.referees
          - @lab.referee_approval_processes.each do |c|
            - if c.referee_lab.present? and c.id
              .col-lg-4
                %p
                  = image_tag c.referee_lab.avatar.thumb('90x90#').url, class: 'avatar tiny center-block'
                %p
                  = link_to link_to c.referee_lab, c.referee_lab


  %fieldset
    %legend Status and history of your Lab
    .row
      .col-lg-12
        %h5
          Current status of your Lab
        %p
          Is this Lab already open, planned or closed?

        .row
          - Lab::ACTIVITY_STATUS.each do |status|
            .col-lg-2
              .radio-inline
                %span
                  = f.radio_button :activity_status, status, class: 'activity-status-radio'
                  %label.radio{style: "width: 160px;"}
                    = status.humanize.titleize

        .row
          .col-lg-12
            %h5
              History of your Lab
            %p
              Please indicate these important dates in the history of your Lab:
        .row
          .col-lg-4
            = f.input :activity_start_at, label: 'When did you start designing and planning your Lab?', as: 'string', input_html: {class: 'datepicker', "data-date-format" => "yyyy-mm-dd"}
          .col-lg-4
            = f.input :activity_inaugurated_at, label: 'When was the Lab officially inaugurated?', as: 'string', input_html: {class: 'datepicker' , "data-date-format" => "yyyy-mm-dd"}
          .col-lg-4
            = f.input :activity_closed_at, label: 'When was the Lab closed?', as: 'string', input_html: {class: 'datepicker' , "data-date-format" => "yyyy-mm-dd"}

  %fieldset
    %legend Location
    .row
      .col-lg-12
        = f.input :address_1
        = f.input :address_2
        = f.input :city
        = f.input :county
        = f.input :postal_code
        = f.input :country_code, as: 'country', label: 'Country', iso_codes: true
        = f.input :latitude
        = f.input :longitude
        = f.input :zoom
        = f.input :address_notes

  %fieldset
    %legend Capabilities
    .row
      .col-lg-12
        = f.input :tools_list

  %fieldset
    %legend Contact information
    .row
      .col-lg-12
        = f.input :phone
        = f.input :email

  %fieldset
    %legend Notes
    .row
      .col-lg-12
        = f.input :application_notes

  %fieldset
    %legend Referee status
    .row
      .col-lg-12
        = f.input :is_referee


  .row
    .col-lg-12
      = f.submit 'save', class: 'btn btn-success'

app/views/backstage/labs/index.html.haml
.row
  .col-lg-12
    = render "backstage/header"
    = title "Labs"

    = render 'backstage/labs/labs', q: @q, url_form: [:backstage, :labs], labs: @labs

app/views/backstage/labs/show.html.haml
.row
  .col-lg-12
    = render "backstage/header"
    = title @lab
    %table.table
      %tr
        %th State
        %td
          = @lab.current_state
          - @lab.current_state.events.keys.each do |event|
            - if current_user.is_referee? or current_user.is_unique_referee?
              - if ['referee_approves', 'request_more_info', 'referee_requests_admin_approval', 'referee_rejects'].include? event.to_s
                = button_to "#{event.capitalize.to_s.tr('_', ' ')}", {controller: 'labs', action: event}, method: :patch, class: 'btn btn-success', id: 'event'
            - if current_user.has_role? :superadmin
              - if ['approve', 'request_more_info', 'reject', 'remove'].include? event.to_s
                = button_to "#{event.capitalize.to_s.tr('_', ' ')}", {controller: 'labs', action: event}, method: :patch, class: 'btn btn-success', id: 'event'
      - if @lab.referee.present?
        %tr
          %th Referee
          %td= @lab.referee
      - if @lab.referee_approval_processes.present?
        %tr
          %th Referees
        - @lab.referee_approval_processes.each do |c|
          - if c.referee_lab.present? and c.id
            %tr
              %th
                = image_tag c.referee_lab.avatar.thumb("90x90#").url, class: 'avatar tiny'
              %td
                = link_to link_to c.referee_lab, c.referee_lab
                = c.action

      %tr
        %th Avatar
        %td= image_tag @lab.avatar.url, class: 'avatar med'

      - if @lab.header.present?
        %tr
          %th Header
          %td= image_tag @lab.header.url, class: 'avatar med'
      %tr
        %th Slug
        %td= @lab.slug
      %tr
        %th Creator
        %td= link_to @lab.creator, @lab.creator
      - if @lab.application_notes.present?
        %tr
          %th Application Notes
          %td= @lab.application_notes
      %tr
        %th Description
        %td= @lab.description
      - if @lab.links.any?
        %tr
          %th URLS
          %td
            %ul
              - @lab.links.each do |link|
                %li= link_to link.url, link.url
      - if @lab.phone.present?
        %tr
          %th Phone
          %td= @lab.phone
      - if @lab.email.present?
        %tr
          %th Email
          %td= mail_to @lab.email, @lab.email
      %tr
        %th Address
        %td= @lab.formatted_address
      - if @lab.address_notes.present?
        %tr
          %th Address Notes
          %td= @lab.address_notes
      %tr
        %th Employees
        %td
          %ul
            - @lab.employees.each do |employee|
              = content_tag_for :li, employee do
                = link_to employee.user, employee.user
                = employee.job_title
      %tr
        %th Created At
        %td= @lab.created_at
      %tr
        %th Updated At
        %td= @lab.updated_at
      %tr
        %th Discourse sync
        %td
          = @lab.discourse_id
          %pre
            = @lab.discourse_errors
    - if current_user.has_role? :superadmin
      = link_to edit_backstage_lab_path(@lab), class: 'btn btn-success' do
        = fa_icon "edit", text: "Edit Lab"